### PR TITLE
#17: Implement complete PNG rendering pipeline

### PR DESCRIPTION
**Pull request by pierrepebay**
Fixes: #17

### CODE REVIEW

**Comment by pierrepebay** [comment]
Example of a PNG rendered with `vt-tv`'s latest changes to it's rendering pipeline:

Screenshot 2023-09-14 at 13 12 46

**Comment by ppebay** [comment]
Is the edge set complete? And are the endpoints correct? No glyphs are visible there. On 2023. Sep 14., at 19:24, Pierre L.P. Pébay ***@***.***> wrote:﻿
@lifflander @stmcgovern @ppebay Here is an example of a PNG rendered with vt-tv's latest changes to it's rendering pipeline:

**Comment by pierrepebay** [comment]
As mentioned in the meeting, this issue is that the non-migratable objects are not glyphed correctly and thus not visible at the end of the communication edges.

**Comment by pierrepebay** [comment]
Here is now the current `LBAF` vs `vt-tv` outputed PNG comparaison:
`LBAF` |  `vt-tv`
:-------:|:-------:
 |

**Comment by pierrepebay** [comment]
In `vt-tv`, the actual pixel size of the outputted image can now be user-defined; it is 1 to 1, in the sense that the inputted number is the actual number of pixels per side of the png.

This custom output size is interesting for its improved user-experience, but also because it can enable the user to speed up the execution:
For example, when specifying a 2400\*2400px image (`LBAF`s default and unchangeable value), for this dateset (7 phases), the total `vt-tv` runtime on my machine is on average `5.3s`; on the other hand, by specifying a 1000\*1000px output, this is reduced to `1.9s`.

**Comment by ppebay** [comment]
@pierrepebay following discussion we had on the topic (which I surmise resolved it), please assign this PR to one ore more reviewer(s)

**Review by lifflander — APPROVED** [review]

**Pull request merged**
